//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankDBApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class accounts
    {
        public int account_number { get; set; }
        public string account_name { get; set; }
        public int account_type { get; set; }
        public Nullable<decimal> credit_limit { get; set; }
        public Nullable<decimal> account_saldo { get; set; }
        public int customer_number { get; set; }
    
        public virtual customers customers { get; set; }
    }
}
